# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j5mC7lI0nT39-9z8HvCWotm5WpHjXyZ9
"""

import numpy as np
import matplotlib.pyplot as plt

# Dataset (House size vs price)
X = np.array([500, 800, 1000, 1200, 1500, 1800])
Y = np.array([100, 150, 200, 220, 300, 360])

# Normalize
X = (X - np.mean(X)) / np.std(X)

# Initialize parameters
theta_0 = 0
theta_1 = 0
learning_rate = 0.01
epochs = 100

m = len(X)
loss_history = []

# Gradient Descent
for epoch in range(epochs):
    Y_pred = theta_0 + theta_1 * X

    loss = (1/(2*m)) * np.sum((Y_pred - Y)**2)
    loss_history.append(loss)

    d_theta_0 = (1/m) * np.sum(Y_pred - Y)
    d_theta_1 = (1/m) * np.sum((Y_pred - Y) * X)

    theta_0 -= learning_rate * d_theta_0
    theta_1 -= learning_rate * d_theta_1

print("Final Equation:")
print(f"y = {theta_0:.2f} + {theta_1:.2f}x")

# Plot graph
plt.plot(range(epochs), loss_history)
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Loss vs Epoch")
plt.savefig("loss_plot.png")
plt.show()